const paragraphs = []
paragraphs[0] = "For a while, the only sound were utensils scraping against plates and Wilbur’s heartbeat in his ears.\nHe would never admit it to Tommy or anyone, but his relationship with Father was always better\nwith his brother around. It wasn’t that Wilbur didn’t love his father, or that he thought his father\ndidn’t love him. Wilbur couldn’t remember it happening, but somewhere along the way of\nstudying warfare and politics, of staring up at the throne that would one day be his, of learning how\nto be a prince, he’d forgotten how to be a son.";
paragraphs[1] = "Tommy’s initial annoyance at sleeping in and “missing the Blade in action” was only matched by\nhis absolute delight at seeing his older brother so battered, and then exceeded by his excitement\nwhen Father invited Technoblade for breakfast to recount how terribly Wilbur had performed. It\nwas to track his progress, or some sort of excuse like that, though Wilbur guessed Father just\nwanted to stop Technoblade from disappearing wherever he goes off to—like last night.";
paragraphs[2] = "For a moment, all Wilbur could feel was a sudden, all-consuming affection—not for anything in\nparticular. For everything. For the brilliant spinning wheel in the sky turning everything into\nburnished gold. For the soft dirt beneath his hands. For the air in his lungs and the pollen on his\ntongue. For the distant sound of his brother’s footsteps. For the boy sitting beside him that, against\nall odds, Wilbur found he might actually like beyond mere tolerance. For the levity that had started\nto chase away the more exhausting thoughts.";
paragraphs[3] = "“I’m not done yet!” Tommy said, and produced one more flower—a single yellow rose. “This\none’s my favorite,” he added as he gently tucked the flower behind Technoblade’s ear, the one that\nhad the emerald earring that Wilbur had found so familiar, “because it means friendship.”";
paragraphs[4] = "Mother? Wilbur was on his feet at once, his heart hammering in his chest like a moth set aflame.\nSure enough, there was Mother, out in the sun once more, for the first time in over a year. Wilbur\ntook in a shaky inhale, not daring to breathe again, as if the image before him would dissipate like\nsmoke: Mother, smiling at them, as she walked arm-in-arm with Father through the garden.";
paragraphs[5] = "Wilbur’s arms trembled. He looked down at his brother’s sleeping face— sleeping? Sleeping? He\nisn’t sleeping. He’s dead. Dead. With a rattling breath, Wilbur traced the curve of Tommy’s cheek,\nstopping where it used to dimple when he smiled. And then Wilbur looked down, at where a knife\nstill jutted out of his chest like a violent reminder. Fresh tears stung his eyes, and he tried\ndesperately to blink them away before they could fall. And still a rebel tear found its way down his\nface, carving his dirty cheek in half.";
paragraphs[6] = "Tommy began to weave the morning glories he’d found into Techno’s hair, to hide the fact that his\nhands had started shaking. Two nights before had been the worst of it. Tommy had been awoken\nby the noise of glass shattering. Opening his eyes, he found Wilbur standing over his cot, a shard of\nbroken glass clutched in his hand and raised over his head, ready to strike it into Tommy’s chest.";
paragraphs[7] = "Philza turned to watch his son weaving between the trees. He couldn’t help the laugh that exploded\nout of him at the sight of his youngest son’s arms piled high with apples, toppling to the ground\nwith every excited step he took. By the time he reached Phil, he only had a handful left with him,\nthe rest leaving a trail of red through the orchard.";
paragraphs[8] = "“You’re right,” Techno murmured, too tired to care about what he was saying. “I’m not myself.\nI’m not even a fraction what I used to be. I hate this fragile body and all its whining and all its petty\ndemands.” He looked up, met Wilbur’s eyes, willing him to understand, because there was no way\nin hell he could ever speak the words himself. He didn’t have the vocabulary for it. “I hate being\nthis weak, Wilbur.”"

function generate(){
    myText = document.getElementById("paragraph")
    myText.innerHTML = paragraphs[Math.floor(Math.random()*9)];
}